version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /home/ubuntu/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Change this password as needed

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
     ports:
      - "9100:9100"

volumes:
  prometheus_data:
-- INSERT --                                            
